music_directory    "/srv/iso-mounter/mpd/25bb7eca-d663-11ea-8fc1-97fed6673f2a/music"
playlist_directory "/srv/iso-mounter/mpd/25bb7eca-d663-11ea-8fc1-97fed6673f2a/playlists"
db_file            "/srv/iso-mounter/mpd/25bb7eca-d663-11ea-8fc1-97fed6673f2a/tag_cache"
state_file         "/srv/iso-mounter/mpd/25bb7eca-d663-11ea-8fc1-97fed6673f2a/state"
sticker_file       "/srv/iso-mounter/mpd/25bb7eca-d663-11ea-8fc1-97fed6673f2a/sticker.sql"
pid_file                "/run/mpd/pid"
log_file                "/var/log/mpd/mpd.log"
user                    "mpd"

# Input #######################################################################

input {
        plugin          "curl"
}

input {
        enabled         "no"
        plugin          "qobuz"
}

input {
        enabled         "no"
        plugin          "tidal"
}

decoder {
        plugin          "hybrid_dsd"
        enabled         "no"
}

# Audio Output ################################################################

audio_output {
       type		"pulse"
       name		"Pulse via TCP"
       server		"192.168.0.105"
}

filesystem_charset      "UTF-8"
