music_directory    "/srv/iso-mounter/mpd/00fe2f82-d50b-11ea-8799-1774e1f0005c/music"
playlist_directory "/srv/iso-mounter/mpd/00fe2f82-d50b-11ea-8799-1774e1f0005c/playlists"
db_file            "/srv/iso-mounter/mpd/00fe2f82-d50b-11ea-8799-1774e1f0005c/tag_cache"
state_file         "/srv/iso-mounter/mpd/00fe2f82-d50b-11ea-8799-1774e1f0005c/state"
sticker_file       "/srv/iso-mounter/mpd/00fe2f82-d50b-11ea-8799-1774e1f0005c/sticker.sql"
pid_file                "/run/mpd/pid"
log_file                "/var/log/mpd/mpd.log"
user                    "mpd"

# Input #######################################################################

input {
        plugin          "curl"
}

input {
        enabled         "no"
        plugin          "qobuz"
}

input {
        enabled         "no"
        plugin          "tidal"
}

decoder {
        plugin          "hybrid_dsd"
        enabled         "no"
}

# Audio Output ################################################################

audio_output {
       type		"pulse"
       name		"Pulse via TCP"
       server		"192.168.0.105"
}

filesystem_charset      "UTF-8"
